remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme 
gems:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: "Survey of EcoEvo societies - DEI structures" 
description: Information about the project
show_downloads: [true] 